all:
	g++ *.cpp -o InsertionSort

run_1:
	./InsertionSort instancias-num/num.1000.1.in

run_2:
	./InsertionSort instancias-num/num.1000.2.in

run_3:
	./InsertionSort instancias-num/num.1000.3.in

run_4:
	./InsertionSort instancias-num/num.1000.4.in

run_5:
	./InsertionSort instancias-num/num.10000.1.in

run_6:
	./InsertionSort instancias-num/num.10000.2.in

run_7:
	./InsertionSort instancias-num/num.10000.3.in

run_8:
	./InsertionSort instancias-num/num.10000.4.in

run_9:
	./InsertionSort instancias-num/num.100000.1.in

run_10:
	./InsertionSort instancias-num/num.100000.2.in

run_11:
	./InsertionSort instancias-num/num.100000.3.in

run_12:
	./InsertionSort instancias-num/num.100000.4.in
